<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ithil.Attributes\Ithil.Attributes.csproj" />
    <ProjectReference Include="..\..\src\Ithil.Hosting\Ithil.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Ithil.SourceGenerator\Ithil.SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
