using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ithil.SourceGenerator;

[Generator]
public class AgentToolGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor NonPublicMethodWarning = new(
        id: "ITHIL001",
        title: "Non-public AgentTool method",
        messageFormat: "Method '{0}' is decorated with [AgentTool] but it is not public. It will not be included in the schema registry.",
        category: "Ithil",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);
        
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var allAnnotatedMethods = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Ithil.Attributes.AgentToolAttribute",
                predicate: (node, _) => node is MethodDeclarationSyntax,
                transform: (ctx, _) => {
                    if (ctx.TargetSymbol is not IMethodSymbol method) return null;
                    var attribute = ctx.Attributes.FirstOrDefault();
                    return attribute is null ? null : new AnnotatedMethod(method, attribute);
                })
            .Where(m => m != null);

        // Report warnings for non-public methods
        context.RegisterSourceOutput(
            allAnnotatedMethods
                .Where(m => m!.Method.DeclaredAccessibility != Accessibility.Public)
                .Collect(),
            (ctx, methods) =>
            {
                foreach (var m in methods)
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        NonPublicMethodWarning,
                        m!.Method.Locations.FirstOrDefault() ?? Location.None,
                        m.Method.Name));
            });
                
        // Generate schema for public methods only
        var tools = allAnnotatedMethods
            .Where(m => m!.Method.DeclaredAccessibility == Accessibility.Public)
            .Select(ExtractToolMetadata)
            .Where(t => t != null)
            .Collect();
            
        context.RegisterSourceOutput(tools, GenerateSchemaRegistry);
    }

    private static ToolMetadata? ExtractToolMetadata(AnnotatedMethod? annotated, System.Threading.CancellationToken _)
    {  
        if (annotated is null) return null;

        var method = annotated.Method;
        var attribute = annotated.Attribute;
      
        var description = attribute.ConstructorArguments.Length > 0
            ? attribute.ConstructorArguments[0].Value?.ToString() ?? string.Empty
            : string.Empty;

        var allowWrite = GetNamedBool(attribute, "AllowWrite");
        var maxTokens = GetNamedInt(attribute, "MaxResponseTokens", 2000);
        var category = GetNamedString(attribute, "Category");

        var parameters = method.Parameters
            .Select(p => 
            {
                var (jsonType, format) = TypeMapper.ToJsonType(p.Type);
                var isNullable = p.Type.NullableAnnotation == NullableAnnotation.Annotated
                    || p.HasExplicitDefaultValue;

                return new ParameterMetadata(p.Name, jsonType, format, !isNullable);
            })
            .ToArray();
            
        return new ToolMetadata(
            method.Name,
            description,
            allowWrite,
            maxTokens,
            category,
            Array.Empty<string>(),
            parameters);
    }

    private static void GenerateSchemaRegistry(
        SourceProductionContext context,
        ImmutableArray<ToolMetadata?> tools)
    {
        var validTools = tools.Where(t => t != null).ToArray();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine("namespace Ithil.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class SchemaRegistry");
        sb.AppendLine("{");
        sb.AppendLine("    public static IReadOnlyList<ToolEntry> Tools { get; } = new List<ToolEntry>");
        sb.AppendLine("    {");

        foreach(var tool in validTools)
        {
            sb.AppendLine("        new ToolEntry");
            sb.AppendLine("        {");
            sb.AppendLine($"            Name = \"{tool!.MethodName}\",");
            sb.AppendLine($"            Description = \"{Escape(tool.Description)}\",");
            sb.AppendLine($"            AllowWrite = {tool.AllowWrite.ToString().ToLower()},");
            sb.AppendLine($"            MaxResponseTokens = {tool.MaxResponseTokens},");
            sb.AppendLine($"            Category = {(tool.Category == null ? "null" : $"\"{tool.Category}\"")},");
            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public class ToolEntry");
        sb.AppendLine("{");
        sb.AppendLine("    public string Name { get; set; } = string.Empty;");
        sb.AppendLine("    public string Description { get; set; } = string.Empty;");
        sb.AppendLine("    public bool AllowWrite { get; set; }");
        sb.AppendLine("    public int MaxResponseTokens { get; set; }");
        sb.AppendLine("    public string? Category { get; set; }");
        sb.AppendLine("}");

        context.AddSource("SchemaRegistry.g.cs", sb.ToString());
    }

    private static bool GetNamedBool(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(a => a.Key == name);
        return arg.Key != null && arg.Value.Value is bool b && b;
    }

    private static int GetNamedInt(AttributeData attr, string name, int defaultValue)
    {
        var arg = attr.NamedArguments.FirstOrDefault(a => a.Key == name);
        return arg.Key != null && arg.Value.Value is int i ? i : defaultValue;
    }

    private static string? GetNamedString(AttributeData attr, string name)
    {
        var arg = attr.NamedArguments.FirstOrDefault(a => a.Key == name);
        return arg.Key != null ? arg.Value.Value?.ToString() : null;
    }

    private static string Escape(string s) => s.Replace("\"", "\\\"");
}
