<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.17.0" />
    <PackageReference Include="MudBlazor" Version="9.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ithil.Core\Ithil.Core.csproj" />
    <ProjectReference Include="..\Ithil.Budget\Ithil.Budget.csproj" />
    <ProjectReference Include="..\Ithil.Management\Ithil.Management.csproj" />
  </ItemGroup>

</Project>
